env:
  - FLUTTER_GITHUB="https://github.com/flutter/flutter.git"
  - FLUTTER_PATH="./flutter/bin"

language: dart

dart:
  - stable

dart_task:
  - dartfmt

install:
  - git clone $FLUTTER_GITHUB -b stable

script:
  - $FLUTTER_PATH/flutter doctor
  - $FLUTTER_PATH/flutter test