env:
  - FLUTTER_GITHUB="https://github.com/flutter/flutter.git"

language: dart

dart:
  - stable

dart_task:
  - dartfmt

jobs:
  include:
    - stage: Flutter Test
      language: dart
      os: linux
      install: git clone $FLUTTER_GITHUB -b stable
      before_script:
        - ./flutter/bin/flutter doctor
      script: 
        - ./flutter/bin/flutter test
    # - stage: Integration Test on Android
    #   os: linux
    #   dist: trusty
    #   language: android
    #   android:
    #     components:
    #       - build-tools-28.0.3
    #       - android-28
    #   install: git clone $FLUTTER_GITHUB -b stable
    #   before_script:
    #     - ./flutter/bin/flutter doctor
    #   script: ./flutter/bin/flutter drive --target=test_driver/app.dart