language: dart

dart:
  - stable

dart_task:
  - dartfmt

# dist: trusty

# addons:
#   apt:
#     packages:
#       - lib32stdc++6

# install:
#   - git clone https://github.com/flutter/flutter.git -b stable
# #   - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter test

# script:
#   - flutter test