name: flutter_demo_improved

description: >-
  A better version of the Flutter Demo.
  It features: more organized structure; unit, widget and integration tests; 
  state management with the Provider package; and CI with Travis.

version: 1.0.3

environment:
  sdk: ">=2.5.1 <3.0.0"
  flutter: ^1.12.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4