name: basic_flutter_tdd

description: >-
  A better version of the Flutter Demo.
  It features: better tests, more organized structure, state management with the
  Provider package.

version: 1.0.0+1

environment:
  sdk: ">=2.5.1 <3.0.0"
  flutter: ^1.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true